# Generated by Django 6.0.5 on 2026-05-08 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(choices=[('email', 'Email'), ('webpage', 'Webpage')], default='email', max_length=10)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhishingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('educational_tip', models.TextField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='phishing_sim.phishingscenario')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicators_found', models.IntegerField(default=0)),
                ('total_indicators', models.IntegerField(default=0)),
                ('score_percent', models.FloatField(default=0.0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing_sim.phishingscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phishing_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
