# Generated by Django 6.0.5 on 2026-05-08 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_score', models.IntegerField()),
                ('strength_label', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('has_uppercase', models.BooleanField(default=False)),
                ('has_lowercase', models.BooleanField(default=False)),
                ('has_digits', models.BooleanField(default=False)),
                ('has_symbols', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
